name: PlatformIO CI

on:
  push:
    branches:
      - main
    paths:
      - Configuration.h
      - Configuration_adv.h
      - platformio.ini
      - .github/workflows/platformio.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: MarlinFirmware/Marlin
          ref: bugfix-2.1.x
          path: marlin
      - uses: actions/checkout@v3
        with:
          path: config
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Copy Config Files over
        run: |
          cp -f ./config/platformio.ini ./marlin/ &&
          cp -f ./config/Configuration.h ./marlin/Marlin &&
          cp -f ./config/Configuration_adv.h ./marlin/Marlin
      - name: Build PlatformIO Project
        working-directory: ./marlin
        run: pio run
      - uses: actions/checkout@v3
      - uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: ./marlin/.pio/build/STM32G0B1RE_btt/firmware.bin
